name: 'Cachix'
description: 'nix-build with the help of caching to Cachix'
author: 'Domen Kožar'
inputs:
  name:
    description: 'Name of a cachix cache to push and pull/substitute'
    required: true
  authToken:
    description: 'Authentication token for Cachix, needed only for private cache access'
  signingKey:
    description: 'Signing key secret retrieved after creating binary cache on https://cachix.org'
  skipNixBuild:
    description: 'Set to true to not invoke nix-build after setup.'
  file:
    description: 'Nix file to build. Defaults to default.nix'
  attributes:
    description: 'Nix attributes to nix-build. By default, all attributes are built.'
  nixBuildArgs:
    description: 'Additional arguments for nix-build.'
branding:
  color: 'blue'
  icon: 'database'
runs:
  using: 'node12'
  main: 'lib/main.js'
