name: "cachix-action test"
on:
  pull_request:
  push:    
    branches:
      - master

jobs:
  public-cache:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - run: yarn install --frozen-lockfile
    - run: yarn build
    # check if typescript generation was committed
    - run: git diff --exit-code
    - uses: cachix/install-nix-action@v12
    - name: Test public cache
      uses: ./
      with:
        name: cachix-action
        installCommand: nix-env -if https://github.com/cachix/cachix/tarball/6e46d070ea04bccb557c1b02e9024f5d1b555272 --substituters 'https://cache.nixos.org https://cachix.cachix.org' --trusted-public-keys 'cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY='
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build test.nix

  public-cache-no-signing-key:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - uses: cachix/install-nix-action@v12
    - name: Test public cache no signing key
      uses: ./
      with:
        installCommand: nix-env -if https://github.com/cachix/cachix/tarball/6e46d070ea04bccb557c1b02e9024f5d1b555272 --substituters 'https://cache.nixos.org https://cachix.cachix.org' --trusted-public-keys 'cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY='
        name: cachix-action
    - run: nix-build test.nix

  private-cache:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - uses: cachix/install-nix-action@v12
    - name: Test private cache
      uses: ./
      with:
        name: cachix-action-private
        installCommand: nix-env -if https://github.com/cachix/cachix/tarball/6e46d070ea04bccb557c1b02e9024f5d1b555272 --substituters 'https://cache.nixos.org https://cachix.cachix.org' --trusted-public-keys 'cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY='
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY_PRIVATE }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build test.nix

  installCommand:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - uses: cachix/install-nix-action@v12
    - name: Test private cache
      uses: ./
      with:
        name: cachix-action
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        installCommand: 'nix-env -j8 -f https://cachix.org/api/v1/install -iA cachix'
    - run: nix-build test.nix
